[package]
name = "verdant"
version = "2.3.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
walkdir = "2.0"  # For traversing directories
regex = "1.0" 
chrono = { version = "0.4.41", features = ["serde"] }
